version: "3.8"

services:

  mongodb:
    container_name: "mongodb"
    hostname: "mongodb"
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_db:/data/db
      - ./mongodb_configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  node:
    container_name: "node"
    hostname: "node"
    image: node:17.3
    tty: true
    restart: always
    stop_grace_period: 5s
    ports:
      - 3000:3000
    volumes:
      - ./node_src:/src
    working_dir: "/src/mongo"

  insertdata:
    container_name: "insertdata"
    hostname: "insertdata"
    # image: python:3.10.2
    build: "./insertdata_Dockerfile"
    tty: true
    restart: always
    stop_grace_period: 5s
    # ports:
    #   - 3000:3000
    volumes:
      - ./insertdata_src:/src
    working_dir: "/src"
